# Generated by Django 3.1.7 on 2021-04-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Checkmate in 2 moves'), (2, 'Checkmate in 3 moves'), (3, 'Checkmate in 4 moves')])),
                ('citation', models.TextField()),
                ('fen', models.CharField(max_length=92)),
                ('solution', models.TextField()),
            ],
        ),
    ]
